apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fq6qj9hkg-java-quarkus-gitops
  description: This is GitOps manifest for fq6qj9hkg-java-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=fq6qj9hkg-java-quarkus
    backstage.io/kubernetes-id: fq6qj9hkg-java-quarkus 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fq6qj9hkg-java-quarkus
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fq6qj9hkg-java-quarkus
